image: python

stages:
- test
- build

before_script:
- curl -O https://bootstrap.pypa.io/get-pip.py
- python get-pip.py
- pip install -r requirements_dev.txt

python35:
    image: python:3.5
    stage: test
    script: tox -e py35

python36:
    image: python:3.6
    stage: test
    script: tox -e py36

linter:
    image: python:3.6
    stage: test
    script: tox -e flake8

build:
  stage: build
  script: tox -e build
  artifacts:
    paths:
    - dist/
    expire_in: 1 week
