fail_fast: true  # stops checks if one fails

repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--diff, --check]
        exclude: (^test/|^docs/)
 
  - repo: local
    hooks:             
      - id: flakeheaven
        name: flakeheaven
        entry: flakeheaven lint
        types: [python]
        files: ^{{cookiecutter.project_slug}}/
        language: python
        additional_dependencies: [flakeheaven==1.0.1]
        stages: [push, commit]
