repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
        - id: flake8
        - id: end-of-file-fixer
        - id: requirements-txt-fixer
        - id: pretty-format-json
          args: ['--autofix', '--no-sort-keys']
        - id: check-byte-order-marker
        - id: check-merge-conflict
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
        additional_dependencies: [toml]
