name: python-lint
on:
  push:
    branches:
      - "main"
    paths:
      - '**.py'
      - '.github/workflows/pylint.yml'
  pull_request:
    branches: 
      - "main"
    paths:
      - '**.py'
      - '.github/workflows/pylint.yml'
jobs:
  pylint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./{{ cookiecutter.project_slug }}"
          version: "~= 23.1.0"
