name: python-lint
on:
  push:
    branches:
      - "main"
    paths:
      - '**.py'
  pull_request:
    branches: 
      - "main"
    paths:
      - '**.py'
jobs:
  pylint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./agents_profile_updated/src"
          version: "~= 22.0"
