# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on:
  push:
    branches: 
      - main
    paths:
      - '**.py'
  pull_request:
    branches:
      - main
    paths:
      - '**.py'

jobs:
  test:

    runs-on: ubuntu-latest
    container: python:3
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip install -e ".[test]"
    - name: Run tests with Pytest
      run: |
        make coverage
    - name: Doctests
      run: make doctest
