name: Test {{ cookiecutter.project_slug }}

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "**/requirements_dev.txt"

      - name: Install dev dependencies
        run: |
          pip install ".[dev]" -r requirements.txt -r requirements_dev.txt

      - name: pytest
        run: pytest
