__title__ = "{{ cookiecutter.project_name }}"
__description__ = "{{ cookiecutter.project_short_description }}"
__url__ = "https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}"
__author__ = "{{ cookiecutter.full_name.replace('\"', '\\\"') }}"
__email__ = "{{ cookiecutter.email }}"
__version__ = "{{ cookiecutter.version }}"
