name: Feature Request
description: Suggest something new for the template.
title: "FEAT: "
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: What should the generated project include or do differently?
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: What problem does this solve? What's the use case?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
    validations:
      required: false
