name: Lint

on:
    pull_request:
        branches: ['**']

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
        -   name: Set up Github Workspace
            uses: actions/checkout@v3
            with:
                fetch-depth: 0
        -   name: Set up Python Environment 3.9
            uses: actions/setup-python@v2
            with:
                python-version: 3.9
        -   name: Setup Node Dependency
            uses: actions/setup-node@v2
        -   name: Install Python Dependencies
            run: |
                python -m pip install --upgrade pip wheel
                python -m pip install tox
        -   name: Lint with Flake8
            id: flake8
            continue-on-error: true
            run: |
                echo "::add-matcher::.github/matchers/flake8.json"
                tox -e flake8
                echo "::remove-matcher owner=flake8::"
        -   name: Lint with MyPy
            id: mypy
            continue-on-error: true
            run: |
                echo "::add-matcher::.github/matchers/mypy.json"
                tox -e mypy
                echo "::remove-matcher owner=mypy::"
        -   name: Raise Errors For Linting Failures
            if: |
                steps.flake8.outcome != 'success' ||
                  steps.mypy.outcome != 'success'
            run: |
                echo "Flake8: ${{"{{"}} steps.flake8.outcome {{"}}"}}"
                echo "MyPy: ${{"{{"}} steps.mypy.outcome {{"}}"}}"
                exit 1
