name: Release and Publish

on:
    push:
        branches:
        -   {{ cookiecutter.default_branch }}

jobs:

    Release:
        runs-on: ubuntu-latest
        steps:
        -   name: Set up Github Workspace
            uses: actions/checkout@v3
            with:
                fetch-depth: 0
        -   name: Set up Python
            uses: actions/setup-python@v2
            with:
                python-version: '3.9'
        -   name: Install Dependencies
            run: |
                pip install --upgrade pip
                pip install packaging poetry
        -   name: Setup Git Config
            run: |
                git config --global user.name "github-actions[bot]"
                git config --global user.email "github-actions[bot]@users.noreply.github.com"
        -   name: Update Version Variable
            run: |
                PROJECT_VERSION=$(poetry version --short)
                REPLACED_VERSION_FILE_TEXT=$(grep -F -v "__version__" {{ cookiecutter.project_slug }}/_version.py)
                echo "${REPLACED_VERSION_FILE_TEXT}" > {{ cookiecutter.project_slug }}/_version.py
                echo "__version__ = \""${PROJECT_VERSION}\""" >> {{ cookiecutter.project_slug }}/_version.py
                git add {{ cookiecutter.project_slug }}/_version.py
                git commit -m "Version Bump - ${PROJECT_VERSION}" || true
                git push
        -   name: Declare Version Variable
            run: |
                PROJECT_VERSION=$(poetry version --short)
                PROJECT_NAME=$(poetry version | awk '{ print $2 }')
                echo PROJECT_VERSION=${PROJECT_VERSION} >> $GITHUB_ENV
                echo PROJECT_NAME=${PROJECT_NAME} >> $GITHUB_ENV
        -   name: Tag Setter
            run: |
                echo PROJECT_TAG='v${{"{{"}} env.PROJECT_VERSION {{"}}"}}' >> ${GITHUB_ENV}
                echo PROJECT_RELEASE='${{"{{"}} env.PROJECT_NAME {{"}}"}} v${{"{{"}} env.PROJECT_VERSION {{"}}"}}' >> ${GITHUB_ENV}
        -   name: Draft a Release
            uses: release-drafter/release-drafter@v5
            with:
                config-name: release-drafter.yaml
                name: ${{"{{"}} env.PROJECT_RELEASE {{"}}"}}
                version: ${{"{{"}} env.PROJECT_VERSION {{"}}"}}
                tag: ${{"{{"}} env.PROJECT_TAG {{"}}"}}
                publish: true
            env:
                GITHUB_TOKEN: ${{"{{"}} secrets.{{ cookiecutter.personal_access_token_secret_name }} {{"}}"}}


