name: tests

on:
  push:
    branches:
      - master
    # paths:
    #   - '**.py'
  pull_request:
    branches:
      - master
    # paths:
    #   - '**.py'

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.8
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip install -r requirements_dev.txt
    - name: Run tests with Pytest
      run: |
        python -m pytest tests
